//
//  JDServices-Bridging-Header.h
//  JDServices
//
//  Created by Bott Sebastian on 2014-11-02
//
//  Copyright (c) Deere & Company as an unpublished work
//  THIS SOFTWARE AND/OR MATERIAL IS THE PROPERTY OF
//  DEERE & COMPANY. ALL USE, DISCLOSURE, AND/OR
//  REPRODUCTION NOT SPECIFICALLY AUTHORIZED BY
//  DEERE & COMPANY IS PROHIBITED.
//

#pragma mark mark Common
#import "JDEnvironmentConfiguration.h"
#import "JDServices-Bridging-Header.h"
#import "JDServicesConstants.h"
#import "JDServicesSetup.h"

#pragma mark Utils
#import "JDLocalizedString.h"
#import "JDLogUtils.h"
#import "JDObjectMappingUtils.h"
#import "JDSecretManager.h"
#import "JDUserDefaultUtils.h"
#import "JDWeatherXMLParser.h"
#import "NSBundle+JDServicesBundle.h"

#pragma mark Controller
#import "JDLoginViewController.h"
#import "JDOAuthLoginDelegate.h"
#import "JDOAuthLoginViewController.h"
#import "JDTokenInjectionVC.h"

#pragma mark JD API models
#import "JDAPIBaseObject.h"
#import "JDAccessPoint.h"
#import "JDAddress.h"
#import "JDBoundary.h"
#import "JDBoundingBox.h"
#import "JDClient.h"
#import "JDClients.h"
#import "JDCropType.h"
#import "JDEnabledToggles.h"
#import "JDEquipmentModel.h"
#import "JDEquipmentType.h"
#import "JDExtent.h"
#import "JDFarm.h"
#import "JDFarms.h"
#import "JDField.h"
#import "JDFieldRate.h"
#import "JDFileInfo.h"
#import "JDFileRequestInfo.h"
#import "JDFileResource.h"
#import "JDFirmwareInfo.h"
#import "JDGeoPoint.h"
#import "JDGuidanceLine.h"
#import "JDHarvestAssignment.h"
#import "JDImplement.h"
#import "JDJob.h"
#import "JDJsonObject.h"
#import "JDLocalizedText.h"
#import "JDLocation.h"
#import "JDMachine.h"
#import "JDMachineGeoLocation.h"
#import "JDMachineLocation.h"
#import "JDMachineLocationBreadcrumb.h"
#import "JDMeasurementTotal.h"
#import "JDMetadata.h"
#import "JDMultipolygon.h"
#import "JDNote.h"
#import "JDOperation.h"
#import "JDOperationApplication.h"
#import "JDOperationHarvest.h"
#import "JDOperationProperty.h"
#import "JDOperationSeeding.h"
#import "JDOperationTillage.h"
#import "JDOrganization.h"
#import "JDPoint.h"
#import "JDPossibleAnswer.h"
#import "JDPrescription.h"
#import "JDPrescriptionAssignment.h"
#import "JDProduct.h"
#import "JDProductAssignment.h"
#import "JDProductPackage.h"
#import "JDProperties.h"
#import "JDReorderContainer.h"
#import "JDSeedAssignment.h"
#import "JDSimpleIdentName.h"
#import "JDSimpleName.h"
#import "JDSimpleTypeValue.h"
#import "JDSimpleUnitValue.h"
#import "JDStaff.h"
#import "JDStatusUpdate.h"
#import "JDTerminal.h"
#import "JDTillageType.h"
#import "JDUnitOfMeasureSystem.h"
#import "JDUser.h"
#import "JDWeather.h"
#import "JDWorkAnswer.h"
#import "JDWorkAssignment.h"
#import "JDWorkOrder.h"
#import "JDWorkPlan.h"
#import "JDWorkQuestion.h"
#import "JDWorkQuestionAssignment.h"
#import "JDWorkRecord.h"

#pragma mark Categories
#import "NSError+JDError.h"
#import "NSMutableString+JDObfuscation.h"

#pragma mark Request Helper
#import "AFNetworkingRequestHelper.h"
#import "AFPlainTextResponseSerializer.h"

#pragma mark Requests
#import "JDAccessPointRequests.h"
#import "JDClientRequests.h"
#import "JDCropTypeRequests.h"
#import "JDFieldRequests.h"
#import "JDFileRequests.h"
#import "JDFileResourceRequests.h"
#import "JDFirmwareRequests.h"
#import "JDImplementRequests.h"
#import "JDIncrementalCallbackDelegate.h"
#import "JDJobRequests.h"
#import "JDMachineRequests.h"
#import "JDMobileAccessRequests.h"
#import "JDNoteRequests.h"
#import "JDOAuthHTTPSessionManager.h"
#import "JDOrganizationRequests.h"
#import "JDPreSignedUrlRequests.h"
#import "JDProductRequests.h"
#import "JDRadarRequestManager.h"
#import "JDRequest.h"
#import "JDRequestConfiguration.h"
#import "JDRequestManager.h"
#import "JDResponse.h"
#import "JDStatusUpdateRequests.h"
#import "JDTillageTypeRequests.h"
#import "JDTogglesRequests.h"
#import "JDURL.h"
#import "JDUserRequests.h"
#import "JDWeatherRequestManager.h"
#import "JDWeatherRequests.h"
#import "JDWorkAnswerRequests.h"
#import "JDWorkQuestionRequests.h"

#pragma mark Authentication
#import "GTMOAuthAuthentication.h"
#import "GTMOAuthSignIn.h"
#import "GTMOAuthViewControllerTouch.h"
