//
//  JDServices.h
//  JDServices
//
//  Created by Bott Sebastian on 2015-12-16
//
//  Unpublished Work (c) 2014-2016 Deere & Company.
//  All Worldwide Rights Reserved.
//  THIS MATERIAL IS THE PROPERTY OF DEERE & COMPANY.
//  ALL USE, ALTERATIONS, DISCLOSURE, DISSEMINATION
//  AND/OR REPRODUCTION NOT SPECIFICALLY AUTHORIZED
//  BY DEERE & COMPANY IS PROHIBITED.
//

#import "Foundation/Foundation.h"

#pragma mark mark Common
#import "JDEnvironmentConfiguration.h"
#import "JDServices-Bridging-Header.h"
#import "JDServicesConstants.h"
#import "JDServicesSetup.h"

#pragma mark Utils
#import "JDFileUtils.h"
#import "JDLocalizedString.h"
#import "JDLogUtils.h"
#import "JDObjectMAppingUtils.h"
#import "JDSecretManager.h"
#import "JDServiceDateUtils.h"
#import "JDUserDefaultUtils.h"
#import "JDWeatherXMLParser.h"

#pragma mark Controller
#import "JDEnvironmentSelectionVC.h"
#import "JDLoginViewController.h"
#import "JDOAuthLoginDelegate.h"
#import "JDOAuthLoginViewController.h"
#import "JDTokenInjectionVC.h"

#pragma mark JD API models
#import "JDServices/JDAPIBaseObject.h"
#import "JDServices/JDAccessPoint.h"
#import "JDServices/JDAddress.h"
#import "JDServices/JDAwsAssetLocationsAccessToken.h"
#import "JDServices/JDBoundary.h"
#import "JDServices/JDBoundingBox.h"
#import "JDServices/JDBreadcrumb.h"
#import "JDServices/JDClient.h"
#import "JDServices/JDClients.h"
#import "JDServices/JDContributedMapLayer.h"
#import "JDServices/JDContributedMapLayerSummary.h"
#import "JDServices/JDContributionDefinition.h"
#import "JDServices/JDContributionProduct.h"
#import "JDServices/JDCropType.h"
#import "JDServices/JDDataCollectionMeasurement.h"
#import "JDServices/JDDataCollectionMeasurements.h"
#import "JDServices/JDDisplay.h"
#import "JDServices/JDEmailAddress.h"
#import "JDServices/JDEmailAddresses.h"
#import "JDServices/JDEnabledToggles.h"
#import "JDServices/JDEquipmentApexType.h"
#import "JDServices/JDEquipmentColor.h"
#import "JDServices/JDEquipmentIcon.h"
#import "JDServices/JDEquipmentModel.h"
#import "JDServices/JDEquipmentType.h"
#import "JDServices/JDExtent.h"
#import "JDServices/JDFarm.h"
#import "JDServices/JDFarms.h"
#import "JDServices/JDField.h"
#import "JDServices/JDFieldOperation.h"
#import "JDServices/JDFieldOperationMachine.h"
#import "JDServices/JDFieldOperationMeasurement.h"
#import "JDServices/JDFieldOperationProduct.h"
#import "JDServices/JDFieldRate.h"
#import "JDServices/JDFieldRequestContract.h"
#import "JDServices/JDFileInfo.h"
#import "JDServices/JDFileRequestInfo.h"
#import "JDServices/JDFileResource.h"
#import "JDServices/JDFirmwareInfo.h"
#import "JDServices/JDFlag.h"
#import "JDServices/JDFlagCategory.h"
#import "JDServices/JDFlagCategoryPreference.h"
#import "JDServices/JDFlagGeometry.h"
#import "JDServices/JDGeoJsonGeometry.h"
#import "JDServices/JDGeoJsonLineString.h"
#import "JDServices/JDGeoJsonPoint.h"
#import "JDServices/JDGeoJsonPolygon.h"
#import "JDServices/JDGeoJsonPosition.h"
#import "JDServices/JDGeoPoint.h"
#import "JDServices/JDGuidanceLine.h"
#import "JDServices/JDHarvestAssignment.h"
#import "JDServices/JDIconStyle.h"
#import "JDServices/JDImplement.h"
#import "JDServices/JDJob.h"
#import "JDServices/JDJsonObject.h"
#import "JDServices/JDLocalizedText.h"
#import "JDServices/JDLocation.h"
#import "JDServices/JDMachine.h"
#import "JDServices/JDMachineGeoLocation.h"
#import "JDServices/JDMachineLocation.h"
#import "JDServices/JDMachineLocationBreadcrumb.h"
#import "JDServices/JDMachineStylePreferences.h"
#import "JDServices/JDMapExtent.h"
#import "JDServices/JDMapLegend.h"
#import "JDServices/JDMapLegendItem.h"
#import "JDServices/JDMeasurementTotal.h"
#import "JDServices/JDMetadata.h"
#import "JDServices/JDMultipolygon.h"
#import "JDServices/JDNote.h"
#import "JDServices/JDOperation.h"
#import "JDServices/JDOperationApplication.h"
#import "JDServices/JDOperationHarvest.h"
#import "JDServices/JDOperationProperty.h"
#import "JDServices/JDOperationSeeding.h"
#import "JDServices/JDOperationTillage.h"
#import "JDServices/JDOrganization.h"
#import "JDServices/JDPoint.h"
#import "JDServices/JDPossibleAnswer.h"
#import "JDServices/JDPrescription.h"
#import "JDServices/JDPrescriptionAssignment.h"
#import "JDServices/JDProduct.h"
#import "JDServices/JDProductAssignment.h"
#import "JDServices/JDProductCompany.h"
#import "JDServices/JDProductPackage.h"
#import "JDServices/JDProductTotal.h"
#import "JDServices/JDProperties.h"
#import "JDServices/JDReferenceChemical.h"
#import "JDServices/JDReorderContainer.h"
#import "JDServices/JDSeedAssignment.h"
#import "JDServices/JDSimpleIdentName.h"
#import "JDServices/JDSimpleName.h"
#import "JDServices/JDSimpleTypeValue.h"
#import "JDServices/JDSimpleUnitValue.h"
#import "JDServices/JDStaff.h"
#import "JDServices/JDStatusUpdate.h"
#import "JDServices/JDTask.h"
#import "JDServices/JDTerminal.h"
#import "JDServices/JDTillageType.h"
#import "JDServices/JDUnit.h"
#import "JDServices/JDUnitOfMeasureSystem.h"
#import "JDServices/JDUser.h"
#import "JDServices/JDVariableRepresentation.h"
#import "JDServices/JDVariety.h"
#import "JDServices/JDVarietyTotal.h"
#import "JDServices/JDVersion.h"
#import "JDServices/JDWeather.h"
#import "JDServices/JDWorkAnswer.h"
#import "JDServices/JDWorkAssignment.h"
#import "JDServices/JDWorkOrder.h"
#import "JDServices/JDWorkPlan.h"
#import "JDServices/JDWorkQuestion.h"
#import "JDServices/JDWorkQuestionAssignment.h"
#import "JDServices/JDWorkRecord.h"

#pragma mark Categories
#import "JDServices/NSBundle+JDServicesBundle.h"
#import "JDServices/NSError+JDError.h"
#import "JDServices/NSMutableString+JDObfuscation.h"

#pragma mark Request Helper
#import "JDServices/AFNetworkingRequestHelper.h"
#import "JDServices/AFPlainTextResponseSerializer.h"

#pragma mark Requests
#import "JDProductCompaniesRequestContract.h"
#import "JDProductCompaniesRequests.h"
#import "JDServices/JDAccessPointRequests.h"
#import "JDServices/JDAgencyRegistration.h"
#import "JDServices/JDAwsAssetLocationsAccessTokenRequests.h"
#import "JDServices/JDChemicalRequestContract.h"
#import "JDServices/JDChemicalRequests.h"
#import "JDServices/JDClientRequests.h"
#import "JDServices/JDCropTypeRequests.h"
#import "JDServices/JDFieldOperationRequests.h"
#import "JDServices/JDFieldRequests.h"
#import "JDServices/JDFileRequests.h"
#import "JDServices/JDFileResourceRequests.h"
#import "JDServices/JDFirmwareRequests.h"
#import "JDServices/JDFlagCategoryRequests.h"
#import "JDServices/JDFlagRequests.h"
#import "JDServices/JDImplementRequests.h"
#import "JDServices/JDIncrementalCallbackDelegate.h"
#import "JDServices/JDJobRequests.h"
#import "JDServices/JDMachineRequests.h"
#import "JDServices/JDMachineStylePreferencesRequests.h"
#import "JDServices/JDMapLayerSummariesRequests.h"
#import "JDServices/JDMobileAccessRequests.h"
#import "JDServices/JDNSURLSessionDownloadTaskManager.h"
#import "JDServices/JDNoteRequests.h"
#import "JDServices/JDOAuthHTTPSessionManager.h"
#import "JDServices/JDOrganizationRequests.h"
#import "JDServices/JDPreSignedUrlRequests.h"
#import "JDServices/JDProductRequests.h"
#import "JDServices/JDRadarRequestManager.h"
#import "JDServices/JDRequest.h"
#import "JDServices/JDRequestConfiguration.h"
#import "JDServices/JDRequestManager.h"
#import "JDServices/JDResponse.h"
#import "JDServices/JDStatusUpdateRequests.h"
#import "JDServices/JDTaskRequests.h"
#import "JDServices/JDTillageTypeRequests.h"
#import "JDServices/JDTogglesRequestContract.h"
#import "JDServices/JDTogglesRequests.h"
#import "JDServices/JDURL.h"
#import "JDServices/JDUserRequests.h"
#import "JDServices/JDVariableRepresentationRequests.h"
#import "JDServices/JDVarietyRequestContract.h"
#import "JDServices/JDVarietyRequests.h"
#import "JDServices/JDWeatherRequestManager.h"
#import "JDServices/JDWeatherRequests.h"
#import "JDServices/JDWorkAnswerRequests.h"
#import "JDServices/JDWorkQuestionRequests.h"

#pragma mark Request Parameters
#import "JDServices/JDAwsAssetLocationsAccessTokenRequestContract.h"
#import "JDServices/JDRequestContract.h"

#pragma mark Authentication
#import "JDServices/GTMOAuthAuthentication.h"
#import "JDServices/GTMOAuthSignIn.h"
#import "JDServices/GTMOAuthViewControllerTouch.h"
