# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CallingAPI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CallingAPI
pod 'Alamofire', '~> 4.7'
pod 'OAuthSwift', '~> 1.2.0'

end
